### ISSUE TITLE
Obtaining proto.npy file

### ISSUE THREAD

**Issue by NazirNayal8** [deeplearning-wisc/siren#4]
Greetings, 

Thank you for this great work. 

I tried to run the evaluation scripts in the order as specified in the readme, but when running 

```
python voc_coco_vmf.py --name xxx --pro_length xx --use_trained_params 1
```

it seems to require the `proto.npy` files. From the code it seems that this file is saved in the last epoch of training. Therefore I would like to know what is the correct way to obtain the learned prototypes ?

Many thanks in advance.

**Comment by d12306** [comment]
hi, @NazirNayal8 , thanks for your question! I think after training, you are going to get the proto.npy. It is saved automatically.

**Comment by NazirNayal8** [comment]
Hello @d12306 , thanks for your reply! I am not training from scratch, I am simply trying to run the pretrained checkpoints provided in the readme. Is it possible to share the saved `proto.npy` files for these checkpoints specifically? Many thanks

**Comment by d12306** [comment]
Hi, @NazirNayal8 , the prototypes and kappa for pascal voc as id is uploaded in the code repo. https://github.com/deeplearning-wisc/siren/blob/main/detr/saved_proto_kappa_voc. For bdd100k, you can try yourself because the npy files along with the checkpoints are deleted by a system update.
