### ISSUE TITLE
Can SIREN be applied to yolov6 (1-stage detector) rather than other detectors(Faster-RCNN, DETR)?

### ISSUE THREAD

**Issue by ChangGiMoon** [deeplearning-wisc/siren#8]
Dear authors, 
Can SIREN be applied to yolov6 (1-stage detector) rather than other detectors(Faster-RCNN, DETR)?

**Comment by d12306** [comment]
hi @ChangGiMoon , I think it might be feasible for such extension. since the yolo also has a feature space before the classification head. There are some differences between them as well, such as the training objectives and the meaning of the objects/anchors. You are encouraged to have a try.
